name: HelloCICD
description: An example project that shows how to integrate with external CICD systems
version: 0.0.1
author: scott+data_eng@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: hellocicd
  parentArtefactID: prophecy_demos
  buildSystem: wheel
  author: null
  createdAt: '2023-04-03 15:25:13'
  modifiedAt: '2023-04-03 15:25:13'
pipelines:
  pipelines/IngestData:
    name: IngestData
    description: ''
    author: scott+data_eng@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-03-20 19:43:43'
    modifiedAt: '2023-05-01 19:27:20'
    datasets:
      inputs: []
      outputs:
      - datasets/Carts_Raw
      - datasets/Products_Raw
      - datasets/Users_Raw
    subgraphs: []
    dependencies: {}
  pipelines/Products_RawBronze:
    name: Products_RawBronze
    description: Processes raw Product data into Bronze Layer
    author: scott+data_eng@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-03-20 21:10:10'
    modifiedAt: '2023-05-01 19:27:26'
    datasets:
      inputs:
      - datasets/Products_Raw
      outputs:
      - datasets/Products_Bronze
    subgraphs: []
    dependencies: {}
  pipelines/Carts_RawBronze:
    name: Carts_RawBronze
    description: Processes Cart data into Bronze layer using SCD1
    author: scott+data_eng@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-03-20 21:19:31'
    modifiedAt: '2023-05-01 19:26:05'
    datasets:
      inputs:
      - datasets/Carts_Raw
      outputs:
      - datasets/Carts_Bronze
    subgraphs: []
    dependencies: {}
  pipelines/Users_RawBronze:
    name: Users_RawBronze
    description: Transforms User data from Raw to Bronze Layer
    author: scott+data_eng@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-03-20 22:10:51'
    modifiedAt: '2023-05-01 19:27:32'
    datasets:
      inputs:
      - datasets/Users_Raw
      outputs:
      - datasets/Users_Bronze
    subgraphs: []
    dependencies: {}
datasets:
  datasets/Users_Raw:
    name: Users_Raw
    description: ''
    author: scott+data_eng@prophecy.io
    createdAt: '2023-03-20 20:33:34'
    modifiedAt: '2023-03-22 20:46:25'
    mode: batch
    physicalDatasets:
      HelloDev:
        fabricId: 1726
        datasetType: File
        description: ''
        author: scott+data_eng@prophecy.io
        createdAt: '2023-03-20 20:33:34'
        modifiedAt: '2023-03-20 20:33:34'
  datasets/Products_Raw:
    name: Products_Raw
    description: ''
    author: scott+data_eng@prophecy.io
    createdAt: '2023-03-20 20:34:33'
    modifiedAt: '2023-03-22 20:46:32'
    mode: batch
    physicalDatasets:
      HelloDev:
        fabricId: 1726
        datasetType: File
        description: ''
        author: scott+data_eng@prophecy.io
        createdAt: '2023-03-20 20:34:33'
        modifiedAt: '2023-03-20 20:34:33'
  datasets/Carts_Raw:
    name: Carts_Raw
    description: ''
    author: scott+data_eng@prophecy.io
    createdAt: '2023-03-20 20:37:04'
    modifiedAt: '2023-03-22 20:46:39'
    mode: batch
    physicalDatasets:
      HelloDev:
        fabricId: 1726
        datasetType: File
        description: ''
        author: scott+data_eng@prophecy.io
        createdAt: '2023-03-20 20:37:04'
        modifiedAt: '2023-03-20 20:37:04'
  datasets/Products_Bronze:
    name: Products_Bronze
    description: ''
    author: scott+data_eng@prophecy.io
    createdAt: '2023-03-20 21:17:33'
    modifiedAt: '2023-03-21 23:32:34'
    mode: batch
    physicalDatasets:
      HelloDev:
        fabricId: 1726
        datasetType: Database
        description: ''
        author: scott+data_eng@prophecy.io
        createdAt: '2023-03-20 21:17:33'
        modifiedAt: '2023-03-20 21:17:33'
  datasets/Carts_Bronze:
    name: Carts_Bronze
    description: ''
    author: scott+data_eng@prophecy.io
    createdAt: '2023-03-20 22:08:52'
    modifiedAt: '2023-03-21 23:29:39'
    mode: batch
    physicalDatasets:
      HelloDev:
        fabricId: 1726
        datasetType: Database
        description: ''
        author: scott+data_eng@prophecy.io
        createdAt: '2023-03-20 22:08:52'
        modifiedAt: '2023-03-20 22:08:52'
  datasets/Users_Bronze:
    name: Users_Bronze
    description: ''
    author: scott+data_eng@prophecy.io
    createdAt: '2023-03-20 22:27:28'
    modifiedAt: '2023-03-21 23:04:14'
    mode: batch
    physicalDatasets:
      HelloDev:
        fabricId: 1726
        datasetType: Database
        description: ''
        author: scott+data_eng@prophecy.io
        createdAt: '2023-03-20 22:27:28'
        modifiedAt: '2023-03-20 22:27:28'
templates: {}
jobs:
  jobs/example_job_observability:
    name: example_job_observability
    description: ''
    fabricUID: 1174
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 1/1 * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/Carts_RawBronze
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2023-05-01 19:14:29'
    modifiedAt: '2023-05-01 19:14:33'
    author: rj@prophecy.io
functions:
  author: null
  createdAt: '2023-04-03 15:25:13'
  modifiedAt: '2023-04-03 15:25:13'
  gems: {}
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: []
projectDependencies: {}
pipelineConfigurations: {}
